; Object attributes:
defnum ObjectAttrX             0
defnum ObjectAttrY             1
defnum ObjectAttrZ             2
defnum ObjectAttrMaxVel        3
defnum ObjectAttrStance        4
defnum ObjectAttrWasBlocked    5
defnum ObjectAttrX16           6
defnum ObjectAttrY16           7
defnum ObjectAttrZ16           8
defnum ObjectAttrAngle         9

; Object numbers:
defnum ObjectXBowBolt          108

